---
- name: Generate Switch Configuration File
  template: src=switch_template.j2 dest=/home/dfreedman/class-exercises/Python4NetworkEngineers/week5/separated/NVE/roles/switch/configs/{{item.hostname}}.txt
  with_items: switch_list
