---
- name: Generate Router Configuration File
  template: src=router_template.j2 dest=/home/dfreedman/class-exercises/Python4NetworkEngineers/week5/separated/NVE/roles/router/configs/{{item.hostname}}.txt
  with_items: router_list
